Z3: ast Class Reference
ast Class Reference
C++ API
Public Member Functions
ast (context &c)
ast (context &c, Z3_ast n)
ast (ast const &s)
~ast ()
operator Z3_ast () const
operator bool () const
ast & operator= (ast const &s)
Z3_ast_kind kind () const
unsigned hash () const
Public Member Functions inherited from object
object (context &c)
object (object const &s)
context & ctx () const
void check_error () const
Protected Attributes
Z3_ast m_ast
Protected Attributes inherited from object
context * m_ctx
Friends
std::ostream & operator<< (std::ostream &out, ast const &n)
bool eq (ast const &a, ast const &b)
Return true if the ASTs are structurally identical.
Detailed Description
Definition at line 321 of file z3++.h.
Constructor & Destructor Documentation
ast (context & c) inline
Definition at line 325 of file z3++.h.
 :object(c), m_ast(0) {}
ast (context & c, Z3_ast n) inline
Definition at line 326 of file z3++.h.
 :object(c), m_ast(n) { Z3_inc_ref(ctx(), m_ast); }
ast (ast const & s) inline
Definition at line 327 of file z3++.h.
 :object(s), m_ast(s.m_ast) { Z3_inc_ref(ctx(), m_ast); }
~ast () inline
Definition at line 328 of file z3++.h.
 { if (m_ast) Z3_dec_ref(*m_ctx, m_ast); }
Member Function Documentation
unsigned hash () const inline
Definition at line 333 of file z3++.h.
 { unsigned r = Z3_get_ast_hash(ctx(), m_ast); check_error(); return r; }
Z3_ast_kind kind () const inline
Definition at line 332 of file z3++.h.
Referenced by expr::is_app(), expr::is_numeral(), expr::is_quantifier(), and expr::is_var().
 { Z3_ast_kind r = Z3_get_ast_kind(ctx(), m_ast); check_error(); return r; }
operator bool () const inline
Definition at line 330 of file z3++.h.
 { return m_ast != 0; }
operator Z3_ast () const inline
Definition at line 329 of file z3++.h.
 { return m_ast; }
ast& operator= (ast const & s) inline
Definition at line 331 of file z3++.h.
Referenced by sort::operator=(), func_decl::operator=(), and expr::operator=().
 { Z3_inc_ref(s.ctx(), s.m_ast); if (m_ast) Z3_dec_ref(ctx(), m_ast); m_ctx = s.m_ctx; m_ast = s.m_ast; return *this; }
Friends And Related Function Documentation
bool eq (ast const & a, ast const & b) friend
Return true if the ASTs are structurally identical.
Definition at line 344 of file z3++.h.
Referenced by SortRef::cast(), and BoolSortRef::cast().
 { return Z3_is_eq_ast(a.ctx(), a, b) != 0; }
std::ostream& operator<< (std::ostream & out, ast const & n) friend
Definition at line 334 of file z3++.h.
{
             out << Z3_ast_to_string(n.ctx(), n.m_ast); return out;
         }
Field Documentation
Z3_ast m_ast protected
Definition at line 323 of file z3++.h.
Referenced by expr::get_sort(), expr::is_well_sorted(), expr::operator Z3_app(), ast::operator Z3_ast(), func_decl::operator Z3_func_decl(), sort::operator Z3_sort(), ast::operator=(), expr::simplify(), and expr::substitute().