Z3: FuncDecl.Parameter Class Reference
FuncDecl.Parameter Class Reference
Public Member Functions
int getInt () throws Z3Exception
double getDouble () throws Z3Exception
Symbol getSymbol () throws Z3Exception
Sort getSort () throws Z3Exception
AST getAST () throws Z3Exception
FuncDecl getFuncDecl () throws Z3Exception
String getRational () throws Z3Exception
Z3_parameter_kind getParameterKind () throws Z3Exception
Detailed Description
Function declarations can have Parameters associated with them.
Definition at line 212 of file FuncDecl.java.
Member Function Documentation
AST getAST () throws Z3Exception inline
The AST value of the parameter.
Definition at line 266 of file FuncDecl.java.
         {
             if (getParameterKind() != Z3_parameter_kind.Z3_PARAMETER_AST)
                 throw new Z3Exception("parameter is not an AST");
             return ast;
         }
double getDouble () throws Z3Exception inline
The double value of the parameter.
Definition at line 236 of file FuncDecl.java.
         {
             if (getParameterKind() != Z3_parameter_kind.Z3_PARAMETER_DOUBLE)
                 throw new Z3Exception("parameter is not a double ");
             return d;
         }
FuncDecl getFuncDecl () throws Z3Exception inline
The FunctionDeclaration value of the parameter.
Definition at line 276 of file FuncDecl.java.
         {
             if (getParameterKind() != Z3_parameter_kind.Z3_PARAMETER_FUNC_DECL)
                 throw new Z3Exception("parameter is not a function declaration");
             return fd;
         }
int getInt () throws Z3Exception inline
The int value of the parameter.
Definition at line 226 of file FuncDecl.java.
         {
             if (getParameterKind() != Z3_parameter_kind.Z3_PARAMETER_INT)
                 throw new Z3Exception("parameter is not an int");
             return i;
         }
Z3_parameter_kind getParameterKind () throws Z3Exception inline
The kind of the parameter.
Definition at line 296 of file FuncDecl.java.
Referenced by FuncDecl.Parameter.getAST(), FuncDecl.Parameter.getDouble(), FuncDecl.Parameter.getFuncDecl(), FuncDecl.Parameter.getInt(), FuncDecl.Parameter.getRational(), FuncDecl.Parameter.getSort(), and FuncDecl.Parameter.getSymbol().
         {
             return kind;
         }
String getRational () throws Z3Exception inline
The rational string value of the parameter.
Definition at line 286 of file FuncDecl.java.
         {
             if (getParameterKind() != Z3_parameter_kind.Z3_PARAMETER_RATIONAL)
                 throw new Z3Exception("parameter is not a rational String");
             return r;
         }
Sort getSort () throws Z3Exception inline
The Sort value of the parameter.
Definition at line 256 of file FuncDecl.java.
         {
             if (getParameterKind() != Z3_parameter_kind.Z3_PARAMETER_SORT)
                 throw new Z3Exception("parameter is not a Sort");
             return srt;
         }
Symbol getSymbol () throws Z3Exception inline
The Symbol value of the parameter.
Definition at line 246 of file FuncDecl.java.
         {
             if (getParameterKind() != Z3_parameter_kind.Z3_PARAMETER_SYMBOL)
                 throw new Z3Exception("parameter is not a Symbol");
             return sym;
         }