Z3: ArithRef Class Reference
ArithRef Class Reference
Public Member Functions
def sort
def is_int
def is_real
def __add__
def __radd__
def __mul__
def __rmul__
def __sub__
def __rsub__
def __pow__
def __rpow__
def __div__
def __truediv__
def __rdiv__
def __rtruediv__
def __mod__
def __rmod__
def __neg__
def __pos__
def __le__
def __lt__
def __gt__
def __ge__
Public Member Functions inherited from ExprRef
def as_ast
def get_id
def sort
def sort_kind
def __eq__
def __ne__
def decl
def num_args
def arg
def children
Public Member Functions inherited from AstRef
def __init__
def __del__
def __str__
def __repr__
def sexpr
def as_ast
def get_id
def ctx_ref
def eq
def translate
def hash
Public Member Functions inherited from Z3PPObject
def use_pp
Additional Inherited Members
Data Fields inherited from AstRef
ast
ctx
Detailed Description
Integer and Real expressions.
Definition at line 1917 of file z3py.py.
Member Function Documentation
def __add__ (self, other)
Create the Z3 expression `self + other`.
>>> x = Int('x')
>>> y = Int('y')
>>> x + y
x + y
>>> (x + y).sort()
Int
Definition at line 1955 of file z3py.py.
     def __add__(self, other):
         """Create the Z3 expression `self + other`.
         >>> x = Int('x')
         >>> y = Int('y')
         >>> x + y
         x + y
         >>> (x + y).sort()
         Int
         """
         a, b = _coerce_exprs(self, other)
         return ArithRef(_mk_bin(Z3_mk_add, a, b), self.ctx)
def __div__ (self, other)
Create the Z3 expression `other/self`.
>>> x = Int('x')
>>> y = Int('y')
>>> x/y
x/y
>>> (x/y).sort()
Int
>>> (x/y).sexpr()
'(div x y)'
>>> x = Real('x')
>>> y = Real('y')
>>> x/y
x/y
>>> (x/y).sort()
Real
>>> (x/y).sexpr()
'(/ x y)'
Definition at line 2052 of file z3py.py.
     def __div__(self, other):
         """Create the Z3 expression `other/self`.
         >>> x = Int('x')
         >>> y = Int('y')
         >>> x/y
         x/y
         >>> (x/y).sort()
         Int
         >>> (x/y).sexpr()
         '(div x y)'
         >>> x = Real('x')
         >>> y = Real('y')
         >>> x/y
         x/y
         >>> (x/y).sort()
         Real
         >>> (x/y).sexpr()
         '(/ x y)'
         """
         a, b = _coerce_exprs(self, other)
         return ArithRef(Z3_mk_div(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
def __ge__ (self, other)
Create the Z3 expression `other >= self`.
>>> x, y = Ints('x y')
>>> x >= y
x >= y
>>> y = Real('y')
>>> x >= y
ToReal(x) >= y
Definition at line 2186 of file z3py.py.
     def __ge__(self, other):
         """Create the Z3 expression `other >= self`.
         >>> x, y = Ints('x y')
         >>> x >= y
         x >= y
         >>> y = Real('y')
         >>> x >= y
         ToReal(x) >= y
         """
         a, b = _coerce_exprs(self, other)
         return BoolRef(Z3_mk_ge(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
def __gt__ (self, other)
Create the Z3 expression `other > self`.
>>> x, y = Ints('x y')
>>> x > y
x > y
>>> y = Real('y')
>>> x > y
ToReal(x) > y
Definition at line 2173 of file z3py.py.
     def __gt__(self, other):
         """Create the Z3 expression `other > self`.
         >>> x, y = Ints('x y')
         >>> x > y
         x > y
         >>> y = Real('y')
         >>> x > y
         ToReal(x) > y
         """
         a, b = _coerce_exprs(self, other)
         return BoolRef(Z3_mk_gt(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
def __le__ (self, other)
Create the Z3 expression `other <= self`.
>>> x, y = Ints('x y')
>>> x <= y
x <= y
>>> y = Real('y')
>>> x <= y
ToReal(x) <= y
Definition at line 2147 of file z3py.py.
     def __le__(self, other):
         """Create the Z3 expression `other <= self`.
         >>> x, y = Ints('x y')
         >>> x <= y
         x <= y
         >>> y = Real('y')
         >>> x <= y
         ToReal(x) <= y
         """
         a, b = _coerce_exprs(self, other)
         return BoolRef(Z3_mk_le(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
def __lt__ (self, other)
Create the Z3 expression `other < self`.
>>> x, y = Ints('x y')
>>> x < y
x < y
>>> y = Real('y')
>>> x < y
ToReal(x) < y
Definition at line 2160 of file z3py.py.
     def __lt__(self, other):
         """Create the Z3 expression `other < self`.
         >>> x, y = Ints('x y')
         >>> x < y
         x < y
         >>> y = Real('y')
         >>> x < y
         ToReal(x) < y
         """
         a, b = _coerce_exprs(self, other)
         return BoolRef(Z3_mk_lt(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
def __mod__ (self, other)
Create the Z3 expression `other%self`.
>>> x = Int('x')
>>> y = Int('y')
>>> x % y
x%y
>>> simplify(IntVal(10) % IntVal(3))
1
Definition at line 2100 of file z3py.py.
     def __mod__(self, other):
         """Create the Z3 expression `other%self`.
         >>> x = Int('x')
         >>> y = Int('y')
         >>> x % y
         x%y
         >>> simplify(IntVal(10) % IntVal(3))
         1
         """
         a, b = _coerce_exprs(self, other)
         if __debug__:
             _z3_assert(a.is_int(), "Z3 integer expression expected")
         return ArithRef(Z3_mk_mod(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
def __mul__ (self, other)
Create the Z3 expression `self * other`.
>>> x = Real('x')
>>> y = Real('y')
>>> x * y
x*y
>>> (x * y).sort()
Real
Definition at line 1978 of file z3py.py.
     def __mul__(self, other):
         """Create the Z3 expression `self * other`.
         >>> x = Real('x')
         >>> y = Real('y')
         >>> x * y
         x*y
         >>> (x * y).sort()
         Real
         """
         a, b = _coerce_exprs(self, other)
         return ArithRef(_mk_bin(Z3_mk_mul, a, b), self.ctx)
def __neg__ (self)
Return an expression representing `-self`.
>>> x = Int('x')
>>> -x
-x
>>> simplify(-(-x))
x
Definition at line 2127 of file z3py.py.
     def __neg__(self):
         """Return an expression representing `-self`.
         >>> x = Int('x')
         >>> -x
         -x
         >>> simplify(-(-x))
         x
         """
         return ArithRef(Z3_mk_unary_minus(self.ctx_ref(), self.as_ast()), self.ctx)
def __pos__ (self)
Return `self`.
>>> x = Int('x')
>>> +x
x
Definition at line 2138 of file z3py.py.
     def __pos__(self):
         """Return `self`.
         >>> x = Int('x')
         >>> +x
         x
         """
         return self
def __pow__ (self, other)
Create the Z3 expression `self**other` (** is the power operator).
>>> x = Real('x')
>>> x**3
x**3
>>> (x**3).sort()
Real
>>> simplify(IntVal(2)**8)
256
Definition at line 2024 of file z3py.py.
     def __pow__(self, other):
         """Create the Z3 expression `self**other` (** is the power operator).
         >>> x = Real('x')
         >>> x**3
         x**3
         >>> (x**3).sort()
         Real
         >>> simplify(IntVal(2)**8)
         256
         """
         a, b = _coerce_exprs(self, other)
         return ArithRef(Z3_mk_power(self.ctx_ref(), a.as_ast(), b.as_ast()), self.ctx)
def __radd__ (self, other)
Create the Z3 expression `other + self`.
>>> x = Int('x')
>>> 10 + x
10 + x
Definition at line 1968 of file z3py.py.
     def __radd__(self, other):
         """Create the Z3 expression `other + self`.
         >>> x = Int('x')
         >>> 10 + x
         10 + x
         """
         a, b = _coerce_exprs(self, other)
         return ArithRef(_mk_bin(Z3_mk_add, b, a), self.ctx)
def __rdiv__ (self, other)
Create the Z3 expression `other/self`.
>>> x = Int('x')
>>> 10/x
10/x
>>> (10/x).sexpr()
'(div 10 x)'
>>> x = Real('x')
>>> 10/x
10/x
>>> (10/x).sexpr()
'(/ 10.0 x)'
Definition at line 2079 of file z3py.py.
     def __rdiv__(self, other):
         """Create the Z3 expression `other/self`.
         >>> x = Int('x')
         >>> 10/x
         10/x
         >>> (10/x).sexpr()
         '(div 10 x)'
         >>> x = Real('x')
         >>> 10/x
         10/x
         >>> (10/x).sexpr()
         '(/ 10.0 x)'
         """
         a, b = _coerce_exprs(self, other)
         return ArithRef(Z3_mk_div(self.ctx_ref(), b.as_ast(), a.as_ast()), self.ctx)
def __rmod__ (self, other)
Create the Z3 expression `other%self`.
>>> x = Int('x')
>>> 10 % x
10%x
Definition at line 2115 of file z3py.py.
     def __rmod__(self, other):
         """Create the Z3 expression `other%self`.
         >>> x = Int('x')
         >>> 10 % x
         10%x
         """
         a, b = _coerce_exprs(self, other)
         if __debug__:
             _z3_assert(a.is_int(), "Z3 integer expression expected")
         return ArithRef(Z3_mk_mod(self.ctx_ref(), b.as_ast(), a.as_ast()), self.ctx)
def __rmul__ (self, other)
Create the Z3 expression `other * self`.
>>> x = Real('x')
>>> 10 * x
10*x
Definition at line 1991 of file z3py.py.
     def __rmul__(self, other):
         """Create the Z3 expression `other * self`.
         >>> x = Real('x')
         >>> 10 * x
         10*x
         """
         a, b = _coerce_exprs(self, other)
         return ArithRef(_mk_bin(Z3_mk_mul, b, a), self.ctx)
def __rpow__ (self, other)
Create the Z3 expression `other**self` (** is the power operator).
>>> x = Real('x')
>>> 2**x
2**x
>>> (2**x).sort()
Real
>>> simplify(2**IntVal(8))
256
Definition at line 2038 of file z3py.py.
     def __rpow__(self, other):
         """Create the Z3 expression `other**self` (** is the power operator).
         >>> x = Real('x')
         >>> 2**x
         2**x
         >>> (2**x).sort()
         Real
         >>> simplify(2**IntVal(8))
         256
         """
         a, b = _coerce_exprs(self, other)
         return ArithRef(Z3_mk_power(self.ctx_ref(), b.as_ast(), a.as_ast()), self.ctx)
def __rsub__ (self, other)
Create the Z3 expression `other - self`.
>>> x = Int('x')
>>> 10 - x
10 - x
Definition at line 2014 of file z3py.py.
     def __rsub__(self, other):
         """Create the Z3 expression `other - self`.
         >>> x = Int('x')
         >>> 10 - x
         10 - x
         """
         a, b = _coerce_exprs(self, other)
         return ArithRef(_mk_bin(Z3_mk_sub, b, a), self.ctx)
def __rtruediv__ (self, other)
Create the Z3 expression `other/self`.
Definition at line 2096 of file z3py.py.
     def __rtruediv__(self, other):
         """Create the Z3 expression `other/self`."""
         return self.__rdiv__(other)
def __sub__ (self, other)
Create the Z3 expression `self - other`.
>>> x = Int('x')
>>> y = Int('y')
>>> x - y
x - y
>>> (x - y).sort()
Int
Definition at line 2001 of file z3py.py.
     def __sub__(self, other):
         """Create the Z3 expression `self - other`.
         >>> x = Int('x')
         >>> y = Int('y')
         >>> x - y
         x - y
         >>> (x - y).sort()
         Int
         """
         a, b = _coerce_exprs(self, other)
         return ArithRef(_mk_bin(Z3_mk_sub, a, b), self.ctx)
def __truediv__ (self, other)
Create the Z3 expression `other/self`.
Definition at line 2075 of file z3py.py.
     def __truediv__(self, other):
         """Create the Z3 expression `other/self`."""
         return self.__div__(other)
def is_int (self)
Return `True` if `self` is an integer expression.
>>> x = Int('x')
>>> x.is_int()
True
>>> (x + 1).is_int()
True
>>> y = Real('y')
>>> (x + y).is_int()
False
Definition at line 1930 of file z3py.py.
     def is_int(self):
         """Return `True` if `self` is an integer expression.
         >>> x = Int('x')
         >>> x.is_int()
         True
         >>> (x + 1).is_int()
         True
         >>> y = Real('y')
         >>> (x + y).is_int()
         False
         """
         return self.sort().is_int()
def is_real (self)
Return `True` if `self` is an real expression.
>>> x = Real('x')
>>> x.is_real()
True
>>> (x + 1).is_real()
True
Definition at line 1944 of file z3py.py.
     def is_real(self):
         """Return `True` if `self` is an real expression.
         >>> x = Real('x')
         >>> x.is_real()
         True
         >>> (x + 1).is_real()
         True
         """
         return self.sort().is_real()
def sort (self)
Return the sort (type) of the arithmetical expression `self`.
>>> Int('x').sort()
Int
>>> (Real('x') + 1).sort()
Real
Definition at line 1920 of file z3py.py.
Referenced by ArithRef.__add__(), ArithRef.__div__(), ArithRef.__mul__(), ArithRef.__pow__(), ArithRef.__rpow__(), and ArithRef.__sub__().
     def sort(self):
         """Return the sort (type) of the arithmetical expression `self`.
         >>> Int('x').sort()
         Int
         >>> (Real('x') + 1).sort()
         Real
         """
         return ArithSortRef(Z3_get_sort(self.ctx_ref(), self.as_ast()), self.ctx)