Z3: FuncDeclRef Class Reference
FuncDeclRef Class Reference
Function Declarations.
Public Member Functions
def as_ast
def get_id
def as_func_decl
def name
def arity
def domain
def range
def kind
def __call__
Public Member Functions inherited from AstRef
def __init__
def __del__
def __str__
def __repr__
def sexpr
def as_ast
def get_id
def ctx_ref
def eq
def translate
def hash
Public Member Functions inherited from Z3PPObject
def use_pp
Additional Inherited Members
Data Fields inherited from AstRef
ast
ctx
Detailed Description
Function Declarations.
Function declaration. Every constant and function have an associated declaration.
The declaration assigns a name, a sort (i.e., type), and for function
the sort (i.e., type) of each of its arguments. Note that, in Z3,
a constant is a function with 0 arguments.
Definition at line 587 of file z3py.py.
Member Function Documentation
def __call__ (self, args)
Create a Z3 application expression using the function `self`, and the given arguments.
The arguments must be Z3 expressions. This method assumes that
the sorts of the elements in `args` match the sorts of the
domain. Limited coersion is supported.  For example, if
args[0] is a Python integer, and the function expects a Z3
integer, then the argument is automatically converted into a
Z3 integer.
>>> f = Function('f', IntSort(), RealSort(), BoolSort())
>>> x = Int('x')
>>> y = Real('y')
>>> f(x, y)
f(x, y)
>>> f(x, x)
f(x, ToReal(x))
Definition at line 657 of file z3py.py.
     def __call__(self, *args):
         """Create a Z3 application expression using the function `self`, and the given arguments.
         The arguments must be Z3 expressions. This method assumes that
         the sorts of the elements in `args` match the sorts of the
         domain. Limited coersion is supported.  For example, if
         args[0] is a Python integer, and the function expects a Z3
         integer, then the argument is automatically converted into a
         Z3 integer.
         >>> f = Function('f', IntSort(), RealSort(), BoolSort())
         >>> x = Int('x')
         >>> y = Real('y')
         >>> f(x, y)
         f(x, y)
         >>> f(x, x)
         f(x, ToReal(x))
         """
         args = _get_args(args)
         num = len(args)
         if __debug__:
             _z3_assert(num == self.arity(), "Incorrect number of arguments to %s" % self)
         _args = (Ast * num)()
         saved = []
         for i in range(num):
             # self.domain(i).cast(args[i]) may create a new Z3 expression,
             # then we must save in 'saved' to prevent it from being garbage collected.
             tmp      = self.domain(i).cast(args[i])
             saved.append(tmp)
             _args[i] = tmp.as_ast()
         return _to_expr_ref(Z3_mk_app(self.ctx_ref(), self.ast, len(args), _args), self.ctx)
def arity (self)
Return the number of arguments of a function declaration. If `self` is a constant, then `self.arity()` is 0.
>>> f = Function('f', IntSort(), RealSort(), BoolSort())
>>> f.arity()
2
Definition at line 614 of file z3py.py.
Referenced by FuncDeclRef.__call__(), and FuncDeclRef.domain().
     def arity(self):
         """Return the number of arguments of a function declaration. If `self` is a constant, then `self.arity()` is 0.
         >>> f = Function('f', IntSort(), RealSort(), BoolSort())
         >>> f.arity()
         2
         """
         return int(Z3_get_arity(self.ctx_ref(), self.ast))
def as_ast (self)
Definition at line 594 of file z3py.py.
     def as_ast(self):
         return Z3_func_decl_to_ast(self.ctx_ref(), self.ast)
def as_func_decl (self)
Definition at line 600 of file z3py.py.
     def as_func_decl(self):
         return self.ast
def domain (self, i)
Return the sort of the argument `i` of a function declaration. This method assumes that `0 <= i < self.arity()`.
>>> f = Function('f', IntSort(), RealSort(), BoolSort())
>>> f.domain(0)
Int
>>> f.domain(1)
Real
Definition at line 623 of file z3py.py.
Referenced by FuncDeclRef.__call__(), and ArrayRef.__getitem__().
     def domain(self, i):
         """Return the sort of the argument `i` of a function declaration. This method assumes that `0 <= i < self.arity()`.
         >>> f = Function('f', IntSort(), RealSort(), BoolSort())
         >>> f.domain(0)
         Int
         >>> f.domain(1)
         Real
         """
         if __debug__:
             _z3_assert(i < self.arity(), "Index out of bounds")
         return _to_sort_ref(Z3_get_domain(self.ctx_ref(), self.ast, i), self.ctx)
def get_id (self)
Definition at line 597 of file z3py.py.
     def get_id(self):
         return Z3_get_ast_id(self.ctx_ref(), self.as_ast())
def kind (self)
Return the internal kind of a function declaration. It can be used to identify Z3 built-in functions such as addition, multiplication, etc.
>>> x = Int('x')
>>> d = (x + 1).decl()
>>> d.kind() == Z3_OP_ADD
True
>>> d.kind() == Z3_OP_MUL
False
Definition at line 645 of file z3py.py.
     def kind(self):
         """Return the internal kind of a function declaration. It can be used to identify Z3 built-in functions such as addition, multiplication, etc.
         >>> x = Int('x')
         >>> d = (x + 1).decl()
         >>> d.kind() == Z3_OP_ADD
         True
         >>> d.kind() == Z3_OP_MUL
         False
         """
         return Z3_get_decl_kind(self.ctx_ref(), self.ast)
def name (self)
Return the name of the function declaration `self`.
>>> f = Function('f', IntSort(), IntSort())
>>> f.name()
'f'
>>> isinstance(f.name(), str)
True
Definition at line 603 of file z3py.py.
     def name(self):
         """Return the name of the function declaration `self`.
         >>> f = Function('f', IntSort(), IntSort())
         >>> f.name()
         'f'
         >>> isinstance(f.name(), str)
         True
         """
         return _symbol2py(self.ctx, Z3_get_decl_name(self.ctx_ref(), self.ast))
def range (self)
Return the sort of the range of a function declaration. For constants, this is the sort of the constant.
>>> f = Function('f', IntSort(), RealSort(), BoolSort())
>>> f.range()
Bool
Definition at line 636 of file z3py.py.
Referenced by FuncDeclRef.__call__().
     def range(self):
         """Return the sort of the range of a function declaration. For constants, this is the sort of the constant.
         >>> f = Function('f', IntSort(), RealSort(), BoolSort())
         >>> f.range()
         Bool
         """
         return _to_sort_ref(Z3_get_range(self.ctx_ref(), self.ast), self.ctx)