Z3: DatatypeSort Class Reference
DatatypeSort Class Reference
Public Member Functions
int getNumConstructors () throws Z3Exception
FuncDecl[] getConstructors () throws Z3Exception
FuncDecl[] getRecognizers () throws Z3Exception
FuncDecl[][] getAccessors () throws Z3Exception
Public Member Functions inherited from Sort
boolean equals (Object o)
int hashCode ()
int getId () throws Z3Exception
Z3_sort_kind getSortKind () throws Z3Exception
Symbol getName () throws Z3Exception
String toString ()
Public Member Functions inherited from AST
boolean equals (Object o)
int compareTo (Object other) throws Z3Exception
int hashCode ()
int getId () throws Z3Exception
AST translate (Context ctx) throws Z3Exception
Z3_ast_kind getASTKind () throws Z3Exception
boolean isExpr () throws Z3Exception
boolean isApp () throws Z3Exception
boolean isVar () throws Z3Exception
boolean isQuantifier () throws Z3Exception
boolean isSort () throws Z3Exception
boolean isFuncDecl () throws Z3Exception
String toString ()
String getSExpr () throws Z3Exception
Public Member Functions inherited from Z3Object
void dispose () throws Z3Exception
Public Member Functions inherited from IDisposable
void dispose () throws Z3Exception
Additional Inherited Members
Protected Member Functions inherited from Sort
Sort (Context ctx) throws Z3Exception
Protected Member Functions inherited from Z3Object
void finalize () throws Z3Exception
Detailed Description
Datatype sorts.
Definition at line 23 of file DatatypeSort.java.
Member Function Documentation
FuncDecl [][] getAccessors () throws Z3Exception inline
The constructor accessors.
Exceptions
Z3Exception
Definition at line 69 of file DatatypeSort.java.
         {
                 int n = getNumConstructors();
                 FuncDecl[][] res = new FuncDecl[n][];
                 for (int i = 0; i < n; i++)
                 {
                         FuncDecl fd = new FuncDecl(getContext(),
                                         Native.getDatatypeSortConstructor(getContext().nCtx(),
                                                         getNativeObject(), i));
                         int ds = fd.getDomainSize();
                         FuncDecl[] tmp = new FuncDecl[ds];
                         for (int j = 0; j < ds; j++)
                                 tmp[j] = new FuncDecl(getContext(),
                                                 Native.getDatatypeSortConstructorAccessor(getContext()
                                                                 .nCtx(), getNativeObject(), i, j));
                         res[i] = tmp;
                 }
                 return res;
         }
FuncDecl [] getConstructors () throws Z3Exception inline
The constructors.
Exceptions
Z3Exception
Definition at line 39 of file DatatypeSort.java.
         {
                 int n = getNumConstructors();
                 FuncDecl[] res = new FuncDecl[n];
                 for (int i = 0; i < n; i++)
                         res[i] = new FuncDecl(getContext(), Native.getDatatypeSortConstructor(
                                         getContext().nCtx(), getNativeObject(), i));
                 return res;
         }
int getNumConstructors () throws Z3Exception inline
The number of constructors of the datatype sort.
Definition at line 28 of file DatatypeSort.java.
Referenced by DatatypeSort.getAccessors(), DatatypeSort.getConstructors(), and DatatypeSort.getRecognizers().
         {
                 return Native.getDatatypeSortNumConstructors(getContext().nCtx(),
                                 getNativeObject());
         }
FuncDecl [] getRecognizers () throws Z3Exception inline
The recognizers.
Exceptions
Z3Exception
Definition at line 54 of file DatatypeSort.java.
         {
                 int n = getNumConstructors();
                 FuncDecl[] res = new FuncDecl[n];
                 for (int i = 0; i < n; i++)
                         res[i] = new FuncDecl(getContext(), Native.getDatatypeSortRecognizer(
                                         getContext().nCtx(), getNativeObject(), i));
                 return res;
         }