Z3: Model Class Reference
Model Class Reference
Public Member Functions
Expr getConstInterp (Expr a) throws Z3Exception
Expr getConstInterp (FuncDecl f) throws Z3Exception
FuncInterp getFuncInterp (FuncDecl f) throws Z3Exception
int getNumConsts () throws Z3Exception
FuncDecl[] getConstDecls () throws Z3Exception
int getNumFuncs () throws Z3Exception
FuncDecl[] getFuncDecls () throws Z3Exception
FuncDecl[] getDecls () throws Z3Exception
Public Member Functions inherited from Z3Object
void dispose () throws Z3Exception
Public Member Functions inherited from IDisposable
void dispose () throws Z3Exception
Additional Inherited Members
Protected Member Functions inherited from Z3Object
void finalize () throws Z3Exception
Detailed Description
A Model contains interpretations (assignments) of constants and functions.
Definition at line 25 of file Model.java.
Member Function Documentation
FuncDecl [] getConstDecls () throws Z3Exception inline
The function declarations of the constants in the model.
Exceptions
Z3Exception
Definition at line 129 of file Model.java.
     {
         int n = getNumConsts();
         FuncDecl[] res = new FuncDecl[n];
         for (int i = 0; i < n; i++)
             res[i] = new FuncDecl(getContext(), Native.modelGetConstDecl(getContext()
                     .nCtx(), getNativeObject(), i));
         return res;
     }
Expr getConstInterp (Expr a) throws Z3Exception inline
Retrieves the interpretation (the assignment) of a in the model.
Parameters
a A Constant
Returns
An expression if the constant has an interpretation in the model, null otherwise.
Exceptions
Z3Exception
Definition at line 35 of file Model.java.
     {
         getContext().checkContextMatch(a);
         return getConstInterp(a.getFuncDecl());
     }
Expr getConstInterp (FuncDecl f) throws Z3Exception inline
Retrieves the interpretation (the assignment) of f in the model.
Parameters
f A function declaration of zero arity
Returns
An expression if the function has an interpretation in the model, null otherwise.
Exceptions
Z3Exception
Definition at line 49 of file Model.java.
     {
         getContext().checkContextMatch(f);
         if (f.getArity() != 0
                 || Native.getSortKind(getContext().nCtx(),
                         Native.getRange(getContext().nCtx(), f.getNativeObject())) == Z3_sort_kind.Z3_ARRAY_SORT
                         .toInt())
             throw new Z3Exception(
                     "Non-zero arity functions and arrays have FunctionInterpretations as a model. Use FuncInterp.");
         long n = Native.modelGetConstInterp(getContext().nCtx(), getNativeObject(),
                 f.getNativeObject());
         if (n == 0)
             return null;
         else
             return Expr.create(getContext(), n);
     }
FuncDecl [] getDecls () throws Z3Exception inline
All symbols that have an interpretation in the model.
Exceptions
Z3Exception
Definition at line 167 of file Model.java.
     {
         int nFuncs = getNumFuncs();
         int nConsts = getNumConsts();
         int n = nFuncs + nConsts;
         FuncDecl[] res = new FuncDecl[n];
         for (int i = 0; i < nConsts; i++)
             res[i] = new FuncDecl(getContext(), Native.modelGetConstDecl(getContext()
                     .nCtx(), getNativeObject(), i));
         for (int i = 0; i < nFuncs; i++)
             res[nConsts + i] = new FuncDecl(getContext(), Native.modelGetFuncDecl(
                     getContext().nCtx(), getNativeObject(), i));
         return res;
     }
FuncDecl [] getFuncDecls () throws Z3Exception inline
The function declarations of the function interpretations in the model.
Exceptions
Z3Exception
Definition at line 152 of file Model.java.
     {
         int n = getNumFuncs();
         FuncDecl[] res = new FuncDecl[n];
         for (int i = 0; i < n; i++)
             res[i] = new FuncDecl(getContext(), Native.modelGetFuncDecl(getContext()
                     .nCtx(), getNativeObject(), i));
         return res;
     }
FuncInterp getFuncInterp (FuncDecl f) throws Z3Exception inline
Retrieves the interpretation (the assignment) of a non-constant f in the model.
Parameters
f A function declaration of non-zero arity
Returns
A FunctionInterpretation if the function has an interpretation in the model, null otherwise.
Exceptions
Z3Exception
Definition at line 76 of file Model.java.
     {
         getContext().checkContextMatch(f);
         Z3_sort_kind sk = Z3_sort_kind.fromInt(Native.getSortKind(getContext()
                 .nCtx(), Native.getRange(getContext().nCtx(), f.getNativeObject())));
         if (f.getArity() == 0)
         {
             long n = Native.modelGetConstInterp(getContext().nCtx(),
                     getNativeObject(), f.getNativeObject());
             if (sk == Z3_sort_kind.Z3_ARRAY_SORT)
             {
                 if (n == 0)
                     return null;
                 else
                 {
                     if (Native.isAsArray(getContext().nCtx(), n) ^ true)
                         throw new Z3Exception(
                                 "Argument was not an array constant");
                     long fd = Native.getAsArrayFuncDecl(getContext().nCtx(), n);
                     return getFuncInterp(new FuncDecl(getContext(), fd));
                 }
             } else
             {
                 throw new Z3Exception(
                         "Constant functions do not have a function interpretation; use ConstInterp");
             }
         } else
         {
             long n = Native.modelGetFuncInterp(getContext().nCtx(),
                     getNativeObject(), f.getNativeObject());
             if (n == 0)
                 return null;
             else
                 return new FuncInterp(getContext(), n);
         }
     }
int getNumConsts () throws Z3Exception inline
The number of constants that have an interpretation in the model.
Definition at line 119 of file Model.java.
Referenced by Model.getConstDecls(), and Model.getDecls().
     {
         return Native.modelGetNumConsts(getContext().nCtx(), getNativeObject());
     }
int getNumFuncs () throws Z3Exception inline
The number of function interpretations in the model.
Definition at line 142 of file Model.java.
Referenced by Model.getDecls(), and Model.getFuncDecls().
     {
         return Native.modelGetNumFuncs(getContext().nCtx(), getNativeObject());
     }