Z3: SortRef Class Reference
SortRef Class Reference
Public Member Functions
def as_ast
def get_id
def kind
def subsort
def cast
def name
def __eq__
def __ne__
Public Member Functions inherited from AstRef
def __init__
def __del__
def __str__
def __repr__
def sexpr
def as_ast
def get_id
def ctx_ref
def eq
def translate
def hash
Public Member Functions inherited from Z3PPObject
def use_pp
Additional Inherited Members
Data Fields inherited from AstRef
ast
ctx
Detailed Description
A Sort is essentially a type. Every Z3 expression has a sort. A sort is an AST node.
Definition at line 450 of file z3py.py.
Member Function Documentation
def __eq__ (self, other)
Return `True` if `self` and `other` are the same Z3 sort.
>>> p = Bool('p')
>>> p.sort() == BoolSort()
True
>>> p.sort() == IntSort()
False
Definition at line 508 of file z3py.py.
Referenced by CheckSatResult.__ne__(), and Probe.__ne__().
     def __eq__(self, other):
         """Return `True` if `self` and `other` are the same Z3 sort.
         >>> p = Bool('p')
         >>> p.sort() == BoolSort()
         True
         >>> p.sort() == IntSort()
         False
         """
         if other == None:
             return False
         return Z3_is_eq_sort(self.ctx_ref(), self.ast, other.ast)
def __ne__ (self, other)
Return `True` if `self` and `other` are not the same Z3 sort.
>>> p = Bool('p')
>>> p.sort() != BoolSort()
False
>>> p.sort() != IntSort()
True
Definition at line 521 of file z3py.py.
     def __ne__(self, other):
         """Return `True` if `self` and `other` are not the same Z3 sort.
         >>> p = Bool('p')
         >>> p.sort() != BoolSort()
         False
         >>> p.sort() != IntSort()
         True
         """
         return not Z3_is_eq_sort(self.ctx_ref(), self.ast, other.ast)
def as_ast (self)
Definition at line 452 of file z3py.py.
     def as_ast(self):
         return Z3_sort_to_ast(self.ctx_ref(), self.ast)
def cast (self, val)
Try to cast `val` as an element of sort `self`.
This method is used in Z3Py to convert Python objects such as integers,
floats, longs and strings into Z3 expressions.
>>> x = Int('x')
>>> RealSort().cast(x)
ToReal(x)
Definition at line 483 of file z3py.py.
     def cast(self, val):
         """Try to cast `val` as an element of sort `self`.
         This method is used in Z3Py to convert Python objects such as integers,
         floats, longs and strings into Z3 expressions.
         >>> x = Int('x')
         >>> RealSort().cast(x)
         ToReal(x)
         """
         if __debug__:
             _z3_assert(is_expr(val), "Z3 expression expected")
             _z3_assert(self.eq(val.sort()), "Sort mismatch")
         return val
def get_id (self)
Definition at line 455 of file z3py.py.
     def get_id(self):
         return Z3_get_ast_id(self.ctx_ref(), self.as_ast())
def kind (self)
Return the Z3 internal kind of a sort. This method can be used to test if `self` is one of the Z3 builtin sorts.
>>> b = BoolSort()
>>> b.kind() == Z3_BOOL_SORT
True
>>> b.kind() == Z3_INT_SORT
False
>>> A = ArraySort(IntSort(), IntSort())
>>> A.kind() == Z3_ARRAY_SORT
True
>>> A.kind() == Z3_INT_SORT
False
Definition at line 459 of file z3py.py.
Referenced by ArithSortRef.is_int(), and ArithSortRef.is_real().
     def kind(self):
         """Return the Z3 internal kind of a sort. This method can be used to test if `self` is one of the Z3 builtin sorts.
         >>> b = BoolSort()
         >>> b.kind() == Z3_BOOL_SORT
         True
         >>> b.kind() == Z3_INT_SORT
         False
         >>> A = ArraySort(IntSort(), IntSort())
         >>> A.kind() == Z3_ARRAY_SORT
         True
         >>> A.kind() == Z3_INT_SORT
         False
         """
         return _sort_kind(self.ctx, self.ast)
def name (self)
Return the name (string) of sort `self`.
>>> BoolSort().name()
'Bool'
>>> ArraySort(IntSort(), IntSort()).name()
'Array'
Definition at line 498 of file z3py.py.
     def name(self):
         """Return the name (string) of sort `self`.
         >>> BoolSort().name()
         'Bool'
         >>> ArraySort(IntSort(), IntSort()).name()
         'Array'
         """
         return _symbol2py(self.ctx, Z3_get_sort_name(self.ctx_ref(), self.ast))
def subsort (self, other)
Return `True` if `self` is a subsort of `other`.
>>> IntSort().subsort(RealSort())
True
Definition at line 475 of file z3py.py.
     def subsort(self, other):
         """Return `True` if `self` is a subsort of `other`.
         >>> IntSort().subsort(RealSort())
         True
         """
         return False